import Foundation

public struct PasteboardGeneration: RawRepresentable, Hashable, Sendable {
    public let rawValue: Int

    public init(rawValue: Int) {
        self.rawValue = rawValue
    }
}

public enum PasteboardTypeIdentifier {
    public static let plainText = "public.utf8-plain-text"
    public static let url = "public.url"
    public static let trackerFreeMarker = "com.vishal.TrackerFree.cleaned-v1"

    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let remoteClipboard = "com.apple.is-remote-clipboard"

    static let allowedContent: Set<String> = [plainText, url]
    static let knownSkipMarkers: Set<String> = [
        concealed,
        transient,
        autoGenerated,
        remoteClipboard,
        trackerFreeMarker,
    ]
}

public enum ClipboardPermissionState: Equatable, Sendable {
    /// Pasteboard privacy gating is not applicable, including isolated named pasteboards.
    case notRequired
    case defaultBehavior
    case ask
    case alwaysAllow
    case alwaysDeny
    case unknown

    public var permitsAutomaticReads: Bool {
        switch self {
        case .notRequired, .alwaysAllow:
            true
        case .defaultBehavior, .ask, .alwaysDeny, .unknown:
            false
        }
    }
}

public struct PasteboardContent: Equatable, Sendable {
    public let plainText: String?
    public let url: String?

    public init(plainText: String? = nil, url: String? = nil) {
        self.plainText = plainText
        self.url = url
    }

    public var isEmpty: Bool {
        plainText == nil && url == nil
    }

    public var combinedUTF8ByteCount: Int {
        (plainText?.utf8.count ?? 0) + (url?.utf8.count ?? 0)
    }
}

public struct PasteboardWriteRequest: Equatable, Sendable {
    public let content: PasteboardContent
    public let includesTrackerFreeMarker: Bool

    public init(content: PasteboardContent, includesTrackerFreeMarker: Bool) {
        self.content = content
        self.includesTrackerFreeMarker = includesTrackerFreeMarker
    }
}

/// A fully constructed item that is ready to commit after the final generation check.
///
/// The platform object is intentionally actor-isolated and never crosses a task boundary.
@MainActor
public final class PasteboardPreparedWrite {
    public let request: PasteboardWriteRequest
    let platformItem: AnyObject?

    init(request: PasteboardWriteRequest, platformItem: AnyObject?) {
        self.request = request
        self.platformItem = platformItem
    }
}

/// Synchronous because every operation participates in one serialized pasteboard transaction.
@MainActor
public protocol PasteboardClient: AnyObject {
    var generation: PasteboardGeneration { get }
    var permissionState: ClipboardPermissionState { get }

    func itemCount() -> Int?
    func typeIdentifiers(forItemAt index: Int) -> [String]?
    func data(forTypeIdentifier typeIdentifier: String, itemAt index: Int) -> Data?

    /// Constructs the complete replacement item before the caller mutates pasteboard ownership.
    func prepareWrite(_ request: PasteboardWriteRequest) -> PasteboardPreparedWrite?

    /// Takes ownership using `.currentHostOnly` and clears the current contents.
    @discardableResult
    func prepareForNewContentsCurrentHostOnly() -> PasteboardGeneration

    /// Writes a previously constructed item.
    func writePrepared(_ preparedWrite: PasteboardPreparedWrite) -> Bool
}
